import { Injectable } from '@nestjs/common';
import type { ProjectLevel, ProjectSection } from '@lernard/shared-types';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

interface RenderProjectPdfInput {
  projectId: string;
  title: string;
  templateName: string;
  subject: string;
  level: ProjectLevel;
  totalMarks: number;
  sections: ProjectSection[];
}

@Injectable()
export class ProjectPdfRendererService {
  async render(input: RenderProjectPdfInput): Promise<Buffer> {
    const document = await PDFDocument.create();
    document.setTitle(input.title);
    document.setSubject(input.subject);
    document.setCreator('Lernard Deterministic PDF Renderer');
    document.setProducer('Lernard API');

    const headingFont = await document.embedFont(StandardFonts.HelveticaBold);
    const bodyFont = await document.embedFont(StandardFonts.Helvetica);

    const pageWidth = 595.28;
    const pageHeight = 841.89;
    const marginX = 54;
    const marginTop = 64;
    const marginBottom = 54;
    const lineHeight = 15;
    const headingColor = rgb(0.11, 0.2, 0.45);
    const bodyColor = rgb(0.15, 0.15, 0.19);

    let page = document.addPage([pageWidth, pageHeight]);
    let cursorY = pageHeight - marginTop;

    const newPage = () => {
      page = document.addPage([pageWidth, pageHeight]);
      cursorY = pageHeight - marginTop;
    };

    const ensureSpace = (lineCount: number, localLineHeight = lineHeight) => {
      const required = lineCount * localLineHeight;
      if (cursorY - required < marginBottom) {
        newPage();
      }
    };

    const drawLines = (
      lines: string[],
      options?: { fontSize?: number; color?: ReturnType<typeof rgb>; font?: typeof bodyFont },
    ) => {
      const fontSize = options?.fontSize ?? 11;
      const color = options?.color ?? bodyColor;
      const font = options?.font ?? bodyFont;

      ensureSpace(lines.length);
      for (const line of lines) {
        page.drawText(line, {
          x: marginX,
          y: cursorY,
          size: fontSize,
          font,
          color,
        });
        cursorY -= lineHeight;
      }
    };

    const wrapText = (text: string, fontSize = 11): string[] => {
      const maxWidth = pageWidth - marginX * 2;
      const normalized = text
        .replace(/\r\n/g, '\n')
        .split('\n')
        .map((line) => line.trim())
        .join('\n');

      const paragraphs = normalized.split('\n');
      const wrapped: string[] = [];

      for (const paragraph of paragraphs) {
        if (paragraph.length === 0) {
          wrapped.push('');
          continue;
        }

        const words = paragraph.split(/\s+/).filter(Boolean);
        let current = '';

        for (const word of words) {
          const candidate = current.length > 0 ? `${current} ${word}` : word;
          const width = bodyFont.widthOfTextAtSize(candidate, fontSize);
          if (width <= maxWidth) {
            current = candidate;
            continue;
          }

          if (current.length > 0) {
            wrapped.push(current);
          }
          current = word;
        }

        if (current.length > 0) {
          wrapped.push(current);
        }
      }

      return wrapped;
    };

    const levelLabel = toLevelLabel(input.level);

    drawLines([input.title], {
      fontSize: 18,
      color: headingColor,
      font: headingFont,
    });
    cursorY -= 4;
    drawLines([
      `Template: ${input.templateName}`,
      `Subject: ${input.subject}`,
      `Level: ${levelLabel}`,
      `Total marks: ${input.totalMarks}`,
      `Project ID: ${input.projectId}`,
    ]);
    cursorY -= 8;

    for (const [index, section] of input.sections.entries()) {
      const sectionHeading = `${index + 1}. ${section.title}`;
      ensureSpace(2);
      drawLines([sectionHeading], {
        fontSize: 13,
        color: headingColor,
        font: headingFont,
      });

      const wrappedBody = wrapText(section.body);
      drawLines(wrappedBody.length > 0 ? wrappedBody : ['']);
      cursorY -= 6;
    }

    const footerText = 'Generated by Lernard deterministic project renderer (v1).';
    for (const pdfPage of document.getPages()) {
      pdfPage.drawText(footerText, {
        x: marginX,
        y: 28,
        size: 9,
        font: bodyFont,
        color: rgb(0.45, 0.45, 0.5),
      });
    }

    const bytes = await document.save();
    return Buffer.from(bytes);
  }
}

function toLevelLabel(level: ProjectLevel): string {
  if (level === 'grade7') {
    return 'Grade 7';
  }
  if (level === 'olevel') {
    return 'O Level';
  }
  return 'A Level';
}
